print()
print()
print("KIOYDIOLABS © 2023")
print()
print(" __          __  _                          _ ")
print(" \ \        / / | |                        | |")
print("  \ \  /\  / /__| | ___ ___  _ __ ___   ___| |")
print("   \ \/  \/ / _ \ |/ __/ _ \| '_ ` _ \ / _ \ |")
print("    \  /\  /  __/ | (_| (_) | | | | | |  __/_|")
print("     \/  \/ \___|_|\___\___/|_| |_| |_|\___(_)")
print("")
print("")
print("Welcome to the 'Guessing Game'")